# profile-independent properties
app:
  name: "@project.artifactId@"
  version: "@project.version@"

# tune JAX-RS infrastructure
spring.jersey.servlet.load-on-startup: 100 # eagerly load JAX-RS servlet
logging.level.org.glassfish.jersey.internal.inject.Providers: error # turn off misleading warning

# management and monitoring via Actuator
management:
  endpoints:
    jmx:
      exposure.exclude: "*"
    web:
      base-path: /management
      exposure.include: configprops, env, health, info, metrics
  endpoint:
    configprops.enabled: true
    env.enabled: true
    health:
      enabled: true
      show-components: always
    info.enabled: true
    metrics.enabled: true
